library(shiny)
library(reticulate)


# Source Python script
source_python("python_code.py")

# UI for the application
ui <- fluidPage(
  titlePanel("Shiny App with R and Python 3.12"),
  
  sidebarLayout(
    sidebarPanel(
      sliderInput("obs", "Number of Observations:", 
                  min = 10, max = 100, value = 50),
      actionButton("generate", "Generate Data")
    ),
    
    mainPanel(
      plotOutput("plot"),
      tableOutput("dataTable"),
      verbatimTextOutput("pythonOutput")
    )
  )
)

# Server logic
server <- function(input, output) {
  
  data <- reactive({
    input$generate
    isolate({
      python_generate_data(input$obs)
    })
  })
  
  output$plot <- renderPlot({
    plot(data()[[1]], data()[[2]], type = 'l', main = "Data generated by Python", xlab = "X", ylab = "Y")
  })
  
  output$dataTable <- renderTable({
    data.frame(X = data()[[1]], Y = data()[[2]])
  })
  
  output$pythonOutput <- renderText({
    paste("This data is generated using Python 3.12 with", python_version())
  })
}

# Run the application 
shinyApp(ui = ui, server = server)
